### ISSUE TITLE
[MCU] Create dummy ASW for demonstration purposes

### ISSUE THREAD

**Issue by AndreasFreund** [amosproj/amos2024ss07-updating-flash-boot-loader#48]
## User story
1. As a software developer
2. I need an ASW firmware
3. So that I can demonstrate the flashing process

## Acceptance criteria
* Blinks LEDs in a pattern (e.g. very fast and alternating), so it can be differentiated from bootloader
* Add struct for version information with magic value as start and end marker
* Test software before changing flash layout
* Correct flash layout (can't use same flash area as bootloader, refer to table from Hella)

## Definition of done (DoD)
- Code review has been completed
- Code has been merged
- Feature branch has been deleted
- Update method signatures in architecture diagram
- MCU & GUI build after merge

## Additional info from meeting notes
Just the struct is relevant for this ticket.

Für die Versionsnummernanzeige haben wir ein struct mit magic numbers vorgeschlagen, das wir dann beim Flashen auf PC-Seite finden und danach an eine andere Stelle auch in den Flash schreiben könnten.
```c
struct data{
	uint64_t magic_number;
	char asw_version[8];
	char asw_version_comment[40]; // e.g. Bremse vorne links
	uint64_t magic_number2;
}
```

**Comment by sebas-rodri** [comment]
ASW dummy software that just blinks and has a struct with a magic number


![Image](https://github.com/amosproj/amos2024ss07-updating-flash-boot-loader/assets/128830580/1cfdb386-6c4b-4236-aac9-eab071afaaaf)



With Hexedit this magic number is found again, so it works. (.elf)


![Image](https://github.com/amosproj/amos2024ss07-updating-flash-boot-loader/assets/128830580/96a03d33-69ab-40d0-b5d5-e1ddb7b25f19)


We can see that the function that is called in main, is written into pfls0_asw_core0


![Image](https://github.com/amosproj/amos2024ss07-updating-flash-boot-loader/assets/128830580/f1eb0763-665e-485e-a31c-0a752205bafe)



While flashing works, we cant see the alternate blinking pattern due to changed flash Layout. (Bootloader still has to jump to ASW)
